version: "3.9"

services:

  app:
    container_name: backend-challenge
    build: .
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
    env_file:
      - ./.env